### ISSUE TITLE
[FEATURE] Satisfaction display update

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim2#146]
## Description

This is a series of small improvements to how the satisfaction is displayed in the info bar.

## Tasks

- [x] Make the satisfaction percentage only render to 1d.p.
- [x] Add a dynamic field that shows the current modifier and its remaining duration
- [x] Highlight the field as red if the satisfaction percentage is negative
- [x] Highlight the field as another highlight colour if the percentage is above 100%
