### ISSUE TITLE
[TEST] Remove deprecated function usage

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim2#152]
## Description

Following the merge of #147. The use of the now deprecated all arg constructor should be removed from the AchievementTests, AchivementManagerTests, and the DefinedAchievementTests. Then the deprecated constructor should be made private and the deprecated tag should be removed so it will be used only internally.

## Tasks

- [x] Remove all references to all arg constructor from AchievementTest.java
- [x] Remove all references to all arg constructor from AchivementManagerTest.java
- [x] Remove all references to all arg constructor from DefinedAchievementTest.java
- [x] Make the constructor private
- [x] Remove the deprecated annotation from the function
- [x] Remove the deprecated annotation from the documentation
