### ISSUE TITLE
Basic event system

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim2#19]
Introduce a basic implementation of the event system by adding the timed choice events.

Each event should contain an option for what happens if choice A | B is selected as well as what happens if the event is ignored.

## Tasks

- [x] Define an event card that contains information about the choices in the event
- [x] Define the choice cards for the event card that has chances of each type of event happening
- [x] Add an event bucket that can be randomly removed from
- [x] Add effects to the choice cards that can affect the game state
- [x] Render the event information to the screen
- [x] Add a timer bar that counts down the time left to make a choice
- [x] Implement ignoring the event as a choice
