### ISSUE TITLE
Basic achievements system

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim2#20]
Implement a basic version of the achievement system. This should only aim to implement achievements that are tied to a single action that happens.

## Tasks

- [x] Create a file in local storage that holds the achievements between game loads
- [x] Apply a bonus to the final score based on the achievements gathered
- [x] Add achievements for single action events
- [x] Add popup animation for the achievement when it has been gotten for the first time
- [x] Store the session achievements in the global achievements file at the end of the game
- [x] #58
