### ISSUE TITLE
Improve satisfaction calculation

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim2#21]
Implement the basic conditions for the needs-focused satisfaction calculation. This requires the number of enrolled students to be unrelated to the number of spaces in the accommodation buildings.

## Tasks

- [x] Allow any number of students to be enrolled in the university
- [x] Add a basic needs object that maintains a calculation of the % of students that are housed, can be fed, and are able to be taught
- [x] Convert this into a satisfaction % by taking the lowest % from the 3 stored in the object
- [x] Update the score calculation to use this object
- [x] #67
