### ISSUE TITLE
Add unit tests for the Achievement system

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim2#58]
## Tasks

- [x] Unit test Achievement class
- [x] Unit test AchievementManager class
- [x] Unit test of DefinedAchievements#getMissingAchievements
