### ISSUE TITLE
Allow for removal of buildings

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim2#6]
The buildings cannot be currently removed from the game world. This functionality should be added.
This should completely remove the building so that all references are dropped so it can be deallocated.

## Tasks

- [x] Add functionality to state objects to allow the buildings to be completely removed
- [x] Add way to change into a removal mode
- [x] Add removal highlight for which building is going to be removed
