### ISSUE TITLE
Basic money system

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim2#7]
Implement a basic system to maintain money as a resource.

## Tasks

- [x] Add money counter to info bar
- [x] Add interval for increasing the money
- [x] Add cost for placing buildings
- [x] #11
